// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: group.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToGroup = `-- name: AddUserToGroup :one
INSERT INTO friend_group_members (
    group_id,
    user_id,
    joined_at,
    role
) VALUES (
    $1, $2, $3, $4
)
RETURNING group_id, user_id, joined_at, role
`

type AddUserToGroupParams struct {
	GroupID  uuid.UUID   `json:"groupId"`
	UserID   uuid.UUID   `json:"userId"`
	JoinedAt pgtype.Date `json:"joinedAt"`
	Role     GroupRole   `json:"role"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) (FriendGroupMember, error) {
	row := q.db.QueryRow(ctx, addUserToGroup,
		arg.GroupID,
		arg.UserID,
		arg.JoinedAt,
		arg.Role,
	)
	var i FriendGroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const createFriendGroup = `-- name: CreateFriendGroup :one
INSERT INTO friend_groups (
    id,
    name,
    date_created,
    owner_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, date_created, owner_id
`

type CreateFriendGroupParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	DateCreated pgtype.Date `json:"dateCreated"`
	OwnerID     uuid.UUID   `json:"ownerId"`
}

func (q *Queries) CreateFriendGroup(ctx context.Context, arg CreateFriendGroupParams) (FriendGroup, error) {
	row := q.db.QueryRow(ctx, createFriendGroup,
		arg.ID,
		arg.Name,
		arg.DateCreated,
		arg.OwnerID,
	)
	var i FriendGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateCreated,
		&i.OwnerID,
	)
	return i, err
}

const deleteFriendGroup = `-- name: DeleteFriendGroup :exec
DELETE FROM friend_groups
WHERE id = $1
`

func (q *Queries) DeleteFriendGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendGroup, id)
	return err
}

const getFriendGroup = `-- name: GetFriendGroup :one
SELECT
    id,
    name,
    date_created,
    owner_id
FROM friend_groups
WHERE id = $1
`

func (q *Queries) GetFriendGroup(ctx context.Context, id uuid.UUID) (FriendGroup, error) {
	row := q.db.QueryRow(ctx, getFriendGroup, id)
	var i FriendGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateCreated,
		&i.OwnerID,
	)
	return i, err
}

const listFriendGroups = `-- name: ListFriendGroups :many
SELECT
    id,
    name,
    date_created,
    owner_id
FROM friend_groups
`

func (q *Queries) ListFriendGroups(ctx context.Context) ([]FriendGroup, error) {
	rows, err := q.db.Query(ctx, listFriendGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendGroup
	for rows.Next() {
		var i FriendGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DateCreated,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
    group_id,
    user_id,
    joined_at,
    role
FROM friend_group_members
WHERE group_id = $1
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]FriendGroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendGroupMember
	for rows.Next() {
		var i FriendGroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.JoinedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT friend_group_members.group_id, friend_group_members.user_id, friend_group_members.joined_at, friend_group_members.role, friend_groups.id, friend_groups.name, friend_groups.date_created, friend_groups.owner_id
FROM friend_group_members
JOIN friend_groups ON friend_group_members.group_id = friend_groups.id
WHERE friend_group_members.user_id = $1
`

type ListUserGroupsRow struct {
	FriendGroupMember FriendGroupMember `json:"friendGroupMember"`
	FriendGroup       FriendGroup       `json:"friendGroup"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.FriendGroupMember.GroupID,
			&i.FriendGroupMember.UserID,
			&i.FriendGroupMember.JoinedAt,
			&i.FriendGroupMember.Role,
			&i.FriendGroup.ID,
			&i.FriendGroup.Name,
			&i.FriendGroup.DateCreated,
			&i.FriendGroup.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM friend_group_members
WHERE group_id = $1
  AND user_id = $2
`

type RemoveUserFromGroupParams struct {
	GroupID uuid.UUID `json:"groupId"`
	UserID  uuid.UUID `json:"userId"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.GroupID, arg.UserID)
	return err
}

const updateFriendGroupName = `-- name: UpdateFriendGroupName :one
UPDATE friend_groups
SET name = $2
WHERE id = $1
RETURNING id, name, date_created, owner_id
`

type UpdateFriendGroupNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateFriendGroupName(ctx context.Context, arg UpdateFriendGroupNameParams) (FriendGroup, error) {
	row := q.db.QueryRow(ctx, updateFriendGroupName, arg.ID, arg.Name)
	var i FriendGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateCreated,
		&i.OwnerID,
	)
	return i, err
}
